baseurl = "http://yetanother.io/"
languageCode = "en-us"
title = "YetAnother.io"
paginate = 5
Copyright = "All rights reserved - 2015"
canonifyurls = true
DisqusShortname = "yetanotherio"

[params]
  description = "Yet Another blog about IT, hacking and anything related or not"
  cover = "images/cover2.jpg"
  author = "Benjamin OLIVIER"
  authorlocation = "France"
  authorwebsite = "http://yetanother.io/"
  bio = "IT engineer and open source enthusiast"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-68528919-1"
[permalinks]
  post = "/:slug/"
